defmodule StarkBank.Transaction.Data do
  @moduledoc """
  Transaction struct

  A Transaction is a transfer of funds between workspaces inside Stark Bank.
  Transactions created by the user are only for internal transactions.
  Other operations (such as transfer or charge-payment) will automatically
  create a transaction for the user which can be retrieved for the statement.
  When you initialize a Transaction, the entity will not be automatically
  created in the Stark Bank API. The 'create' function sends the structs
  to the Stark Bank API and returns the list of created structs.

  Parameters (required):
    amount [integer]: amount in cents to be transferred. ex: 1234 (= R$ 12.34)
    description [string]: text to be displayed in the receiver and the sender statements (Min. 10 characters). ex: "funds redistribution"
    external_id [string]: unique id, generated by user, to avoid duplicated transactions. ex: "transaction ABC 2020-03-30"
    received_id [string]: unique id of the receiving workspace. ex: "5656565656565656"
  Parameters (optional):
    sender_id [string]: unique id of the sending workspace. ex: "8656565656565656"
    tags [list of strings]: list of strings for reference when searching transactions (may be empty). ex: ["abc", "test"]
  Attributes (return-only):
    id [string, default None]: unique id returned when Transaction is created. ex: "7656565656565656"
    fee [integer, default None]: fee charged when transfer is created. ex: 200 (= R$ 2.00)
    status [string, default None]: current boleto status. ex: "registered" or "paid"
    created [DateTime, default None]: creation datetime for the boleto. ex: %DateTime{}
  """
  @enforce_keys [:amount, :description, :external_id, :receiver_id]
  defstruct [:amount, :description, :external_id, :receiver_id, :sender_id, :tags, :id, :fee, :created, :source]
end
