# remove excluded tags to run specific module tests
ExUnit.start(
  exclude: [
    # :keys,
    # :balance,
    # :boleto,
    # :boleto_log,
    # :boleto_payment,
    # :boleto_payment_log,
    # :boleto_holmes,
    # :boleto_holmes_log,
    # :invoice,
    # :invoice_log,
    # :dict_key,
    # :deposit,
    # :deposit_log,
    # :dynamic_brcode,
    # :card_method,
    # :merchant_category,
    # :merchant_country,
    # :corporate_balance,
    # :brcode_payment,
    # :brcode_payment_log,
    # :transaction,
    # :transfer,
    # :transfer_log,
    # :utility_payment,
    # :utility_payment_log,
    # :tax_payment,
    # :tax_payment_log,
    # :darf_payment,
    # :darf_payment_log,
    # :payment_request,
    # :payment_preview,
    # :institution,
    # :webhook,
    # :event,
    # :workspace,
  ]
)

Code.require_file("./test/utils/page.exs")
