defmodule StarkBank.CorporatePurchase.Log do
  alias __MODULE__, as: Log
  alias StarkBank.Utils.Rest
  alias StarkBank.Utils.Check
  alias StarkBank.Utils.API
  alias StarkBank.CorporatePurchase
  alias StarkBank.User.Project
  alias StarkBank.User.Organization
  alias StarkBank.Error

  @moduledoc """
  Groups CorporatePurchase.Log related functions
  """

  @doc """
  Every time a CorporatePurchase entity is updated, a corresponding CorporatePurchase.Log
  is generated for the entity. This log is never generated by the
  user, but it can be retrieved to check additional information
  on the CorporatePurchase.

  ## Attributes:
    - `:id` [string]: unique id returned when the log is created. ex: "5656565656565656"
    - `:purchase` [CorporatePurchase]: CorporatePurchase entity to which the log refers to.
    - `:description` [string]: purchase description. ex: "my_description"
    - `:corporate_transaction_id` [string]: transaction ID related to the CorporateCard.
    - `:errors` [list of Error structs]: list of errors linked to this CorporatePurchase event.
    - `:type` [string]: type of the CorporatePurchase event which triggered the log creation. ex: "approved", "canceled", "confirmed", "denied", "reversed", "voided"
    - `:created` [DateTime]: creation datetime for the log. ex: ~U[2020-03-26 19:32:35.418698Z]
  """
  @enforce_keys [:id, :purchase, :description, :corporate_transaction_id, :errors, :type, :created]
  defstruct [:id, :purchase, :description, :corporate_transaction_id, :errors, :type, :created]

  @type t() :: %__MODULE__{}

  @doc """
  Receive a single CorporatePurchase.Log struct previously created by the Stark Bank API by passing its id

  ## Parameters (required):
    - `id` [string]: struct unique id. ex: "5656565656565656"

  ## Options:
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkBank.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - CorporatePurchase.Log struct with updated attributes
  """
  @spec get(binary, user: Project.t() | Organization.t() | nil) :: {:ok, Log.t()} | {:error, [%Error{}]}
  def get(id, options \\ []) do
    Rest.get_id(resource(), id, options)
  end

  @doc """
  Same as get(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec get!(binary, user: Project.t() | Organization.t() | nil) :: Log.t()
  def get!(id, options \\ []) do
    Rest.get_id!(resource(), id, options)
  end

  @doc """
  Receive a stream of CorporatePurchase.Log structs previously created in the Stark Bank API

  ## Options:
    - `:ids` [list of strings, default nil]: list of CorporatePurchase ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - `:limit` [integer, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
    - `:after` [Date or string, default nil]: date filter for structs created only after specified date. ex: ~D[2020-03-25]
    - `:before` [Date or string, default nil]: date filter for structs created only before specified date. ex: ~D[2020-03-25]
    - `:types` [list of strings, default nil]: filter retrieved structs by types. ex: ["approved", "canceled", "confirmed", "denied", "reversed", "voided"]
    - `:purchase_ids` [list of strings, default nil]: list of CorporatePurchase ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkBank.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - stream of CorporatePurchase.Log structs with updated attributes
  """
  @spec query(
          ids: [binary],
          limit: integer,
          after: Date.t() | binary,
          before: Date.t() | binary,
          types: [binary],
          purchase_ids: [binary],
          user: Project.t() | Organization.t()
        ) ::
          ({:cont, {:ok, [Log.t()]}}
           | {:error, [Error.t()]}
           | {:halt, any}
           | {:suspend, any},
           any ->
             any)
  def query(options \\ []) do
    Rest.get_list(resource(), options)
  end

  @doc """
  Same as query(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec query!(
          ids: [binary],
          limit: integer,
          after: Date.t() | binary,
          before: Date.t() | binary,
          types: [binary],
          purchase_ids: [binary],
          user: Project.t() | Organization.t()
        ) ::
          ({:cont, [Log.t()]} | {:halt, any} | {:suspend, any}, any -> any)
  def query!(options \\ []) do
    Rest.get_list!(resource(), options)
  end

  @doc """
  Receive a list of up to 100 CorporatePurchase.Log structs previously created in the Stark Bank API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:ids` [list of strings, default nil]: list of CorporatePurchase ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - `:limit` [integer, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
    - `:after` [Date or string, default nil]: date filter for structs created only after specified date. ex: ~D[2020-03-25]
    - `:before` [Date or string, default nil]: date filter for structs created only before specified date. ex: ~D[2020-03-25]
    - `:types` [list of strings, default nil]: filter retrieved structs by types. ex: ["approved", "canceled", "confirmed", "denied", "reversed", "voided"]
    - `:purchase_ids` [list of strings, default nil]: list of CorporatePurchase ids to filter logs. ex: ["5656565656565656", "4545454545454545"]
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkBank.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - list of CorporatePurchase.Log structs with updated attributes and cursor to retrieve the next page of CorporatePurchase.Log objects
  """
  @spec page(
          cursor: binary,
          ids: [binary],
          limit: integer,
          after: Date.t() | binary,
          before: Date.t() | binary,
          types: [binary],
          purchase_ids: [binary],
          user: Project.t() | Organization.t()
          ) ::
            {:ok, {binary, [Log.t()]}} | {:error, [%Error{}]}
  def page(options \\ []) do
    Rest.get_page(resource(), options)
  end

  @doc """
  Same as page(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec page!(
          cursor: binary,
          ids: [binary],
          limit: integer,
          after: Date.t() | binary,
          before: Date.t() | binary,
          types: [binary],
          purchase_ids: [binary],
          user: Project.t() | Organization.t()
          ) ::
            [Log.t()]
  def page!(options \\ []) do
    Rest.get_page!(resource(), options)
  end

  @doc false
  def resource() do
    {
      "CorporatePurchaseLog",
      &resource_maker/1
    }
  end

  @doc false
  def resource_maker(json) do
    %Log{
      id: json[:id],
      purchase: json[:purchase] |> API.from_api_json(&CorporatePurchase.resource_maker/1),
      description: json[:description],
      corporate_transaction_id: json[:corporate_transaction_id],
      errors: json[:errors] |> parse_errors(),
      type: json[:type],
      created: json[:created] |> Check.datetime()
    }
  end

  defp parse_errors(nil), do: []

  defp parse_errors(errors) do
    Enum.map(errors, fn
      %Error{} = error -> error
      error -> %Error{code: error["code"], message: error["message"]}
    end)
  end
end
