defmodule StarkBank.MerchantCard.Log do
  alias __MODULE__, as: Log
  alias StarkBank.Utils.Rest
  alias StarkBank.Utils.Check
  alias StarkBank.Utils.API
  alias StarkBank.MerchantCard
  alias StarkBank.User.Project
  alias StarkBank.User.Organization
  alias StarkBank.Error

  @moduledoc """
  Groups MerchantCard.Log related functions
  """

  @doc """
  Every time a MerchantCard entity is updated, a corresponding MerchantCard.Log
  is generated for the entity. This log is never generated by the
  user, but it can be retrieved to check additional information
  on the MerchantCard.

  ## Attributes:
    - `:id` [string]: unique id returned when the log is created. ex: "5656565656565656"
    - `:card` [MerchantCard]: MerchantCard entity to which the log refers to.
    - `:errors` [list of Error structs]: list of errors linked to this MerchantCard event. ex: [%StarkBank.Error{code: "invalidCard", message: "The card was declined"}]
    - `:type` [string]: type of the MerchantCard event which triggered the log creation. ex: "created", "updated"
    - `:created` [DateTime]: creation datetime for the log. ex: ~U[2020-03-26 19:32:35.418698Z]
    - `:updated` [DateTime]: latest update datetime for the log. ex: ~U[2020-03-26 19:32:35.418698Z]
  """
  @enforce_keys [:id, :card, :errors, :type, :created, :updated]
  defstruct [:id, :card, :errors, :type, :created, :updated]

  @type t() :: %__MODULE__{}

  @doc """
  Receive a single MerchantCard.Log struct previously created by the Stark Bank API by passing its id

  ## Parameters (required):
    - `id` [string]: struct unique id. ex: "5656565656565656"

  ## Options:
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkBank.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - MerchantCard.Log struct with updated attributes
  """
  @spec get(binary, user: Project.t() | Organization.t() | nil) :: {:ok, Log.t()} | {:error, [%Error{}]}
  def get(id, options \\ []) do
    Rest.get_id(resource(), id, options)
  end

  @doc """
  Same as get(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec get!(binary, user: Project.t() | Organization.t() | nil) :: Log.t()
  def get!(id, options \\ []) do
    Rest.get_id!(resource(), id, options)
  end

  @doc """
  Receive a stream of MerchantCard.Log structs previously created in the Stark Bank API

  ## Options:
    - `:limit` [integer, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
    - `:card_ids` [list of strings, default nil]: list of MerchantCard ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:after` [Date or string, default nil]: date filter for structs created only after specified date. ex: ~D[2020-03-25]
    - `:before` [Date or string, default nil]: date filter for structs created only before specified date. ex: ~D[2020-03-25]
    - `:types` [list of strings, default nil]: filter retrieved structs by event types. ex: ["created", "updated"]
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkBank.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - stream of MerchantCard.Log structs with updated attributes
  """
  @spec query(
          limit: integer,
          card_ids: [binary],
          after: Date.t() | binary,
          before: Date.t() | binary,
          types: [binary],
          user: Project.t() | Organization.t()
        ) ::
          ({:cont, {:ok, [Log.t()]}}
           | {:error, [Error.t()]}
           | {:halt, any}
           | {:suspend, any},
           any ->
             any)
  def query(options \\ []) do
    Rest.get_list(resource(), options)
  end

  @doc """
  Same as query(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec query!(
          limit: integer,
          card_ids: [binary],
          after: Date.t() | binary,
          before: Date.t() | binary,
          types: [binary],
          user: Project.t() | Organization.t()
        ) ::
          ({:cont, [Log.t()]} | {:halt, any} | {:suspend, any}, any -> any)
  def query!(options \\ []) do
    Rest.get_list!(resource(), options)
  end

  @doc """
  Receive a list of up to 100 MerchantCard.Log structs previously created in the Stark Bank API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:limit` [integer, default 100]: maximum number of structs to be retrieved. Max = 100. ex: 35
    - `:card_ids` [list of strings, default nil]: list of MerchantCard ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:after` [Date or string, default nil]: date filter for structs created only after specified date. ex: ~D[2020-03-25]
    - `:before` [Date or string, default nil]: date filter for structs created only before specified date. ex: ~D[2020-03-25]
    - `:types` [list of strings, default nil]: filter retrieved structs by event types. ex: ["created", "updated"]
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkBank.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - list of MerchantCard.Log structs with updated attributes and cursor to retrieve the next page of MerchantCard.Log objects
  """
  @spec page(
          cursor: binary,
          limit: integer,
          card_ids: [binary],
          after: Date.t() | binary,
          before: Date.t() | binary,
          types: [binary],
          user: Project.t() | Organization.t()
        ) ::
          {:ok, {binary, [Log.t()]}} | {:error, [%Error{}]}
  def page(options \\ []) do
    Rest.get_page(resource(), options)
  end

  @doc """
  Same as page(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec page!(
          cursor: binary,
          limit: integer,
          card_ids: [binary],
          after: Date.t() | binary,
          before: Date.t() | binary,
          types: [binary],
          user: Project.t() | Organization.t()
        ) ::
          [Log.t()]
  def page!(options \\ []) do
    Rest.get_page!(resource(), options)
  end

  @doc false
  def resource() do
    {
      "MerchantCardLog",
      &resource_maker/1
    }
  end

  @doc false
  def resource_maker(json) do
    %Log{
      id: json[:id],
      card: json[:card] |> API.from_api_json(&MerchantCard.resource_maker/1),
      errors: json[:errors] |> parse_errors(),
      type: json[:type],
      created: json[:created] |> Check.datetime(),
      updated: json[:updated] |> Check.datetime()
    }
  end

  defp parse_errors(nil), do: []

  defp parse_errors(errors) do
    Enum.map(errors, fn
      %Error{} = error -> error
      error -> %Error{code: error["code"], message: error["message"]}
    end)
  end
end
