defmodule StarkBank.Payment.Utility.Log.Data do
  @moduledoc """
  UtilityPaymentLog struct

  Every time a UtilityPayment entity is modified, a corresponding UtilityPaymentLog
  is generated for the entity. This log is never generated by the user, but it can
  be retrieved to check additional information on the UtilityPayment.

  Attributes:
    id [string]: unique id returned when the log is created. ex: "5656565656565656"
    payment [UtilityPayment]: UtilityPayment entity to which the log refers to.
    errors [list of strings]: list of errors linked to this BoletoPayment event.
    type [string]: type of the UtilityPayment event which triggered the log creation. ex: "registered" or "paid"
    created [DateTime]: creation datetime for the payment. ex: %DateTime{}
  """
  @enforce_keys [:id, :payment, :errors, :type, :created]
  defstruct [:id, :payment, :errors, :type, :created]
end
