defmodule StarkBank.Split do
  alias __MODULE__, as: Split
  alias StarkBank.Utils.Rest
  alias StarkBank.Utils.Check
  alias StarkBank.User.Project
  alias StarkBank.User.Organization
  alias StarkBank.Error

  @moduledoc """
  Groups Split related functions
  """

  @doc """
  A Split is never created directly by the user: it is generated by the
  parent Invoice or Boleto when the payment is settled, so this struct
  only exists as the return value of get/query/page calls.

  ## Parameters (required):
    - `:amount` [integer]: value to send to receivers. ex: 1000 (= R$ 10.00)
    - `:receiver_id` [string]: split receiver unique id. ex: "5656565656565656"

  ## Attributes (return-only):
    - `:id` [string, default nil]: unique id returned when split is created. ex: "5656565656565656"
    - `:source` [string, default nil]: source receivable which generated this split struct. ex: "5656565656565656"
    - `:external_id` [string, default nil]: unique id, generated by the system, to avoid duplicated splits. ex: "invoice/1234/receiver/5678"
    - `:tags` [list of strings, default nil]: list of strings for tagging
    - `:scheduled` [DateTime, default nil]: payment scheduled date or datetime. ex: ~U[2020-03-10 15:17:03.000000Z]
    - `:status` [string, default nil]: current payment status. ex: "success" or "failed"
    - `:created` [DateTime, default nil]: creation datetime for the payment. ex: ~U[2020-03-10 10:30:00.000000Z]
    - `:updated` [DateTime, default nil]: update datetime for the payment. ex: ~U[2020-03-10 10:30:00.000000Z]
  """
  @enforce_keys [:amount, :receiver_id]
  defstruct [
    :amount,
    :receiver_id,
    :source,
    :external_id,
    :tags,
    :scheduled,
    :status,
    :id,
    :created,
    :updated
  ]

  @type t() :: %__MODULE__{}

  @doc """
  Receive a single Split struct previously created in the Stark Bank API by passing its id

  ## Parameters (required):
    - `id` [string]: struct unique id. ex: "5656565656565656"

  ## Options:
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkBank.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - Split struct with updated attributes
  """
  @spec get(binary, user: Project.t() | Organization.t() | nil) ::
          {:ok, Split.t()} | {:error, [%Error{}]}
  def get(id, options \\ []) do
    Rest.get_id(resource(), id, options)
  end

  @doc """
  Same as get(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec get!(binary, user: Project.t() | Organization.t() | nil) :: Split.t()
  def get!(id, options \\ []) do
    Rest.get_id!(resource(), id, options)
  end

  @doc """
  Receive a stream of Split structs previously created in the Stark Bank API

  ## Options:
    - `:limit` [integer, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
    - `:after` [Date or string, default nil]: date filter for structs created only after specified date. ex: ~D[2020-03-25]
    - `:before` [Date or string, default nil]: date filter for structs created only before specified date. ex: ~D[2020-03-25]
    - `:tags` [list of strings, default nil]: tags to filter retrieved structs. ex: ["tony", "stark"]
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:receiver_ids` [list of strings, default nil]: list of receiver ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:status` [string, default nil]: filter for status of retrieved structs. ex: "success"
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkBank.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - stream of Split structs with updated attributes
  """
  @spec query(
          limit: integer,
          after: Date.t() | binary,
          before: Date.t() | binary,
          tags: [binary],
          ids: [binary],
          receiver_ids: [binary],
          status: binary,
          user: Project.t() | Organization.t()
        ) ::
          ({:cont, {:ok, [Split.t()]}}
           | {:error, [Error.t()]}
           | {:halt, any}
           | {:suspend, any},
           any ->
             any)
  def query(options \\ []) do
    Rest.get_list(resource(), options)
  end

  @doc """
  Same as query(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec query!(
          limit: integer,
          after: Date.t() | binary,
          before: Date.t() | binary,
          tags: [binary],
          ids: [binary],
          receiver_ids: [binary],
          status: binary,
          user: Project.t() | Organization.t()
        ) ::
          ({:cont, [Split.t()]} | {:halt, any} | {:suspend, any}, any -> any)
  def query!(options \\ []) do
    Rest.get_list!(resource(), options)
  end

  @doc """
  Receive a list of up to 100 Split structs previously created in the Stark Bank API and the cursor to the next page.
  Use this function instead of query if you want to manually page your requests.

  ## Options:
    - `:cursor` [string, default nil]: cursor returned on the previous page function call
    - `:limit` [integer, default nil]: maximum number of structs to be retrieved. Unlimited if nil. ex: 35
    - `:after` [Date or string, default nil]: date filter for structs created only after specified date. ex: ~D[2020-03-25]
    - `:before` [Date or string, default nil]: date filter for structs created only before specified date. ex: ~D[2020-03-25]
    - `:tags` [list of strings, default nil]: tags to filter retrieved structs. ex: ["tony", "stark"]
    - `:ids` [list of strings, default nil]: list of ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:receiver_ids` [list of strings, default nil]: list of receiver ids to filter retrieved structs. ex: ["5656565656565656", "4545454545454545"]
    - `:status` [string, default nil]: filter for status of retrieved structs. ex: "success"
    - `:user` [Organization/Project, default nil]: Organization or Project struct returned from StarkBank.project(). Only necessary if default project or organization has not been set in configs.

  ## Return:
    - list of Split structs with updated attributes and cursor to retrieve the next page of Split objects
  """
  @spec page(
          cursor: binary,
          limit: integer,
          after: Date.t() | binary,
          before: Date.t() | binary,
          tags: [binary],
          ids: [binary],
          receiver_ids: [binary],
          status: binary,
          user: Project.t() | Organization.t()
          ) ::
            {:ok, {binary, [Split.t()]}} | {:error, [%Error{}]}
  def page(options \\ []) do
    Rest.get_page(resource(), options)
  end

  @doc """
  Same as page(), but it will unwrap the error tuple and raise in case of errors.
  """
  @spec page!(
          cursor: binary,
          limit: integer,
          after: Date.t() | binary,
          before: Date.t() | binary,
          tags: [binary],
          ids: [binary],
          receiver_ids: [binary],
          status: binary,
          user: Project.t() | Organization.t()
          ) ::
            [Split.t()]
  def page!(options \\ []) do
    Rest.get_page!(resource(), options)
  end

  @doc false
  def resource() do
    {
      "Split",
      &resource_maker/1
    }
  end

  @doc false
  def resource_maker(json) do
    %Split{
      amount: json[:amount],
      receiver_id: json[:receiver_id],
      source: json[:source],
      external_id: json[:external_id],
      tags: json[:tags],
      scheduled: json[:scheduled] |> Check.datetime(),
      status: json[:status],
      id: json[:id],
      created: json[:created] |> Check.datetime(),
      updated: json[:updated] |> Check.datetime()
    }
  end
end
